FROM node:18-alpine
WORKDIR /app

# Copiar dependências
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copiar código
COPY . .

# Build
RUN npm run build

# Produção
EXPOSE 3001
ENV PORT=3001
ENV NODE_ENV=production

CMD ["npm", "run", "start"]
