FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

COPY . .

ENV NEXT_PUBLIC_API_URL=http://localhost:3000

EXPOSE 3001

CMD ["npm", "run", "dev", "--", "-p", "3001"]
